version: '3.1'

services:

  nestjs-project-api:
    container_name: dockerization-nestjs-projec
    build: . #build Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/nestjs-project-api # the volume mirrors the sources into the container so it catches development changes

  database:
    container_name: postgres-db
    image: postgres:11.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestgraphqltest
